### ISSUE TITLE
pubsub Test Case Fail

### ISSUE THREAD

**Issue by jensenchen** [bnoguchi/redis-node#6]
I ran the pubsub test case test/pubsub.vows.js and failed, here was the output,

node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: Client is in Pub/Sub mode. Only Pub/Sub commands are allowed in this mode. Use another client for other commands.
    at Client.sendCommand (/home/redis-node/lib/client.js:450:38)
    at Client.select (/home/redis-node/lib/client.js:374:14)
    at Stream.<anonymous> (/home/redis-node/lib/client.js:188:35)
    at Stream.emit (events.js:27:15)
    at IOWatcher.<anonymous> (net.js:863:16)
    at node.js:634:9

Could you please tell me what was going on?
My node version: 0.3.0
redis version: 2.0.4

**Comment by bnoguchi** [comment]
A client that subscribes to a channel cannot use any other commands beside the SUBSCRIBE command. This is the recommended behavior in the Redis docs.

This error shouldn't be occurring in my tests. Have you pulled my most recent master branch? I did some work on the code a few hours ago. Use "make test" -- see updated README on testing instructions.

**Comment by bnoguchi** [comment]
Ah, it appears I pushed them to my other git server and forgot to push to the github servers. Please check for the updated code now.

**Comment by jensenchen** [comment]
Thank you
But still failed. I guess this error due to my operating system. I am runngin ubuntu in vmware on windows 7. The output was: 

should return the same special characters
      禄 expected '{"a":"枚"}',
        got      '{"a":"枚"' (==) // vows.js:54
  setting and getting multiple bytes
